# Generated by Django 4.2.6 on 2023-10-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100, verbose_name='название урока')),
                ('lesson_description', models.TextField(blank=True, null=True, verbose_name='описание урока')),
                ('lesson_preview', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='превью')),
                ('lesson_video_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
